In [10]:
import numpy as np

num_arr = np.arange(1,21)
print(num_arr)
print(np.flip(num_arr))
print(f'num_arr 내의 모든 원소의 합 : {np.sum(num_arr)}')
print(num_arr.reshape(5,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
num_arr 내의 모든 원소의 합 : 210
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [28]:
n_arr = np.arange(25).reshape(5,5)
print(n_arr)

print(n_arr[0,0])
print(n_arr[4,4])

print(n_arr[:2, :])

print(n_arr[2:, :])

print(n_arr[:, ::2])

print(n_arr[::2, ::2])

print(n_arr[:2,:].reshape(5,2))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0
24
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]
[[ 0  2  4]
 [10 12 14]
 [20 22 24]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
arr = np.ones((6,6))
print(arr)

arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [42]:
n = int(input('2 이상의 n을 입력하시오: '))

arr = np.zeros((n,n))
arr[0::2, 1::2] = 1
arr[1::2, 0::2] = 1

print(arr)

2 이상의 n을 입력하시오:  11


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [43]:
a = [100, 100, 200, 200, 300, 300, 400, 400, 500]
print(np.unique(a))

[100 200 300 400 500]


In [48]:
arr = np.arange(1,11)
print(arr)
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

[ 1  2  3  4  5  6  7  8  9 10]
5.5
8.25
2.8722813232690143


In [52]:
a = np.random.randint(0,10,20)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

[7 9 6 4 6 9 3 1 5 4 1 7 9 0 1 8 2 9 8 6]
5.25
2.9979159427842537
8.9875


In [55]:
import numpy as np

a = np.random.randint(0, 10, 30)
print("배열:", a)

counts = np.bincount(a)
sorted_indices = np.argsort(counts)[::-1]  # 빈도 내림차순 정렬

# 최빈값과 두 번째 최빈값
mode1 = sorted_indices[0]
freq1 = counts[mode1]

mode2 = sorted_indices[1]
freq2 = counts[mode2]

print(f'최빈값은 {mode1}이며, {freq1}번 나타남')
print(f'두 번째 최빈값은 {mode2}이며, {freq2}번 나타남')

배열: [7 7 7 2 3 2 8 3 3 5 5 0 0 3 2 5 6 2 8 2 2 0 8 2 4 5 5 9 0 6]
최빈값은 2이며, 7번 나타남
두 번째 최빈값은 5이며, 5번 나타남


In [58]:
a = np.sort(a)
print(a)

[0 0 0 0 2 2 2 2 2 2 2 3 3 3 3 4 5 5 5 5 5 6 6 7 7 7 8 8 8 9]


In [63]:
import numpy as np

a = np.random.randint(0, 10, 30)
print("배열:", a)

counts = np.bincount(a, minlength=10)  # 0~9까지 모두 포함되도록

print(f'정수: 빈도')
for i in range(10):
    print(f'{i}  :  {counts[i]}')

배열: [8 6 5 2 8 9 7 9 3 8 5 7 4 8 9 0 6 2 3 0 8 8 1 8 8 6 5 7 1 7]
정수: 빈도
0  :  2
1  :  2
2  :  2
3  :  2
4  :  1
5  :  3
6  :  3
7  :  4
8  :  8
9  :  3


In [70]:
import numpy as np

np.random.seed(100)     # 시드 설정
a = np.random.rand(27)    # 0 이상 1 미만의 실수 9개 생성
print(a.reshape(3,3,3))

max = np.max(a)
print(max)
print(np.argmax(a))

[[[0.54340494 0.27836939 0.42451759]
  [0.84477613 0.00471886 0.12156912]
  [0.67074908 0.82585276 0.13670659]]

 [[0.57509333 0.89132195 0.20920212]
  [0.18532822 0.10837689 0.21969749]
  [0.97862378 0.81168315 0.17194101]]

 [[0.81622475 0.27407375 0.43170418]
  [0.94002982 0.81764938 0.33611195]
  [0.17541045 0.37283205 0.00568851]]]
0.9786237847073697
15


In [75]:
a = np.arange(1,26)
a = a.reshape(5,5)
print(a)

print(a.sum(axis=1)) # 행 방향 성분의 합
print(a.sum(axis=0)) # 열 방향 성분의 합

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 15  40  65  90 115]
[55 60 65 70 75]


In [78]:
a = np.arange(0, 32).reshape(4,4,2)
print(a)

#평탄화
a = a.flatten()
print(a[9])
print(a[19])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
9
19


In [84]:
import numpy as np

x1 = [i for i in range(100)]
x2 = [i + np.random.randint(1, 10) for i in range(100)]
x3 = [i + np.random.randint(1,50) for i in range(100)]
x4 = [np.random.randint(1, 100) for i in range(100)]

# 상관계수 행렬 생성
arr = np.corrcoef([x1, x2, x3, x4])

# x1과 나머지(x2~x4)와의 상관계수만 추출
x1_corrs = arr[0, 1:]  # x1과 x2~x4와의 상관계수

# 가장 상관관계가 높은 인덱스 찾기
max_index = np.argmax(x1_corrs) + 1  # +1은 x1은 arr[0]이라 기준이기 때문

print("상관계수 행렬:\n", arr)
print("x1과의 상관계수들:", x1_corrs)
print(f"x1과 가장 상관관계가 높은 리스트는 x{max_index+1}입니다.")
print(f"상관계수: {arr[0, max_index]:.4f}")


상관계수 행렬:
 [[ 1.          0.99624905  0.91019291 -0.01704068]
 [ 0.99624905  1.          0.90378146 -0.01305994]
 [ 0.91019291  0.90378146  1.         -0.01021141]
 [-0.01704068 -0.01305994 -0.01021141  1.        ]]
x1과의 상관계수들: [ 0.99624905  0.91019291 -0.01704068]
x1과 가장 상관관계가 높은 리스트는 x2입니다.
상관계수: 0.9962
