In [1]:
import numpy as np

In [2]:
# 넘파이 ndarray 객체 생성
a = np.array([2,3,4])

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [3]:
b = np.array([[1,2,3],[4,5,6]])
# 2행 3열의 배열
b.shape

(2, 3)

In [7]:
# c,d라는 ndarray객체가 있을 때, 이 두 객체에 사칙연산을 적용
c = np.array([10, 20, 30])
d = np.array([1, 2, 3])
c + d

array([11, 22, 33])

In [8]:
c - d

array([ 9, 18, 27])

In [9]:
c * d

array([10, 40, 90])

In [10]:
c / d

array([10., 10., 10.])