## 2025208017 컴퓨터공학과 김이슬

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a = np.insert(a, 1, [0,0,0], axis=1)
print(a)

[[1 0 2 3]
 [4 0 5 6]
 [7 0 8 9]]


In [3]:
end_row = [10, 11, 12, 13]
a = np.insert(a, a.shape[0], end_row, axis=0)
print(a)

[[ 1  0  2  3]
 [ 4  0  5  6]
 [ 7  0  8  9]
 [10 11 12 13]]


In [4]:
first_row = [-3, -2, -1, 0]
a = np.insert(a, a.shape[-1], first_row, axis=0)
print(a)

[[ 1  0  2  3]
 [ 4  0  5  6]
 [ 7  0  8  9]
 [10 11 12 13]
 [-3 -2 -1  0]]
