### 컴퓨터공학과 2025208017 김이슬

In [1]:
import numpy as np

In [2]:
array = ([[35, 24, 55], [69, 19, 9], [4, 1, 11]])

array_sort = np.sort(array, axis=0)[::-1]
print(array_sort)

[[69 24 55]
 [35 19 11]
 [ 4  1  9]]
