### 컴퓨터공학과 2025208017 김이슬

In [1]:
import numpy as np

In [2]:
mean = 180
std = 13

array = np.random.normal(loc=mean, scale=std, size=(4,3))

print(array)

[[183.79192154 170.93148896 177.55956296]
 [177.76480166 197.61652183 178.69839671]
 [162.12969174 186.70414253 180.02737044]
 [194.34597756 186.6438963  210.29874768]]
